spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create


logging:
  level:
    org.springframework.orm.jpa: DEBUG


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
