name: Java CI with Gradle
on:
  push:
    branches: [ main ]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle      
    - name: Grant execute permission for gradlew
      run: chmod -x Backend/GymPrj/gradlew
    - name: Build with Gradle
      run: |
        cd Backend/GymPrj
        sudo ./gradlew build
    - name: Build Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: qwe199942/dockerepo
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PW }}
        
      
              
  deploy:
    needs: CI
    name: Deploy
    runs-on: [ self-hosted ]
    steps:
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PW }}
      - name: Docker run
        run: |
          docker stop GymPrj && docker rm -fv GymPrj
          docker rmi -f qwe199942/dockerepo
          docker run -d -p 8080:8080 --name GymPrj --restart always qwe199942/dockerepo:latest
